In [7]:
import numpy as np
import scipy.linalg as lin

In [43]:
a = np.diag(np.eye(2))
a

array([1., 1.])

In [38]:
lin.block_diag(*[1]*4, 2)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 2]])

In [35]:
mainMatrix_diag = np.diag([4]*3) + np.diag([-1]*2, 1) + np.diag([-1]*2, -1)
lhs = lin.block_diag(*[mainMatrix_diag]*3)

In [36]:
lhs

array([[ 4, -1,  0,  0,  0,  0,  0,  0,  0],
       [-1,  4, -1,  0,  0,  0,  0,  0,  0],
       [ 0, -1,  4,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  4, -1,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  4, -1,  0,  0,  0],
       [ 0,  0,  0,  0, -1,  4,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  4, -1,  0],
       [ 0,  0,  0,  0,  0,  0, -1,  4, -1],
       [ 0,  0,  0,  0,  0,  0,  0, -1,  4]])